spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    banner-mode: off
  flyway:
    baseline-on-migrate: true
  h2.console:
    enabled: true
    path: '/console'
  datasource:
    url: 'jdbc:h2:file:./todo-db'
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/liquibase/db.changelog-master.xml
server:
  port: 8001